-- v0.2용 적중 기록/추천 저장 스키마
create table if not exists kbo_pick_groups (
  id uuid primary key default gen_random_uuid(),
  pick_date date not null,
  group_type text not null,
  combined_odds numeric,
  status text not null default 'pending' check (status in ('pending','hit','miss','void')),
  created_at timestamptz not null default now()
);

create table if not exists kbo_picks (
  id uuid primary key default gen_random_uuid(),
  group_id uuid references kbo_pick_groups(id) on delete cascade,
  game_id text not null,
  market text not null,
  selection text not null,
  line numeric,
  odds numeric,
  model_probability numeric,
  model_ev numeric,
  grade text,
  result text not null default 'pending' check (result in ('pending','hit','miss','push','void')),
  away_score integer,
  home_score integer,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  settled_at timestamptz
);

create index if not exists kbo_picks_game_id_idx on kbo_picks(game_id);
create index if not exists kbo_pick_groups_date_idx on kbo_pick_groups(pick_date desc);

-- BASEBALL_WALLET_V1
-- 서버 권위형 ⚾ 야구공 지갑 / 거래 장부

create table if not exists public.kbo_baseball_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance bigint not null default 0 check (balance >= 0),
  lifetime_earned bigint not null default 0 check (lifetime_earned >= 0),
  lifetime_spent bigint not null default 0 check (lifetime_spent >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.kbo_baseball_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount bigint not null check (amount <> 0),
  balance_after bigint not null check (balance_after >= 0),
  transaction_type text not null,
  reference_key text,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists kbo_baseball_ledger_reference_unique
  on public.kbo_baseball_ledger (user_id, reference_key)
  where reference_key is not null;

create index if not exists kbo_baseball_ledger_user_created_idx
  on public.kbo_baseball_ledger (user_id, created_at desc);

alter table public.kbo_baseball_wallets enable row level security;
alter table public.kbo_baseball_ledger enable row level security;

create policy "baseball_wallet_select_own"
  on public.kbo_baseball_wallets
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "baseball_ledger_select_own"
  on public.kbo_baseball_ledger
  for select
  to authenticated
  using (auth.uid() = user_id);

-- 클라이언트 INSERT / UPDATE / DELETE 정책은 만들지 않는다.
-- 지급 / 사용 / 환불은 SUPABASE_SECRET_KEY를 사용하는 서버 API에서만 처리한다.

-- 테스트 계정 최초 5,000⚾ 지급
-- reference_key UNIQUE 조건으로 이 SQL을 다시 실행해도 중복 지급되지 않는다.
do $$
declare
  target_user uuid := 'b07e1249-c197-4d0c-9e77-ba310c6147bc';
  grant_amount bigint := 5000;
  new_balance bigint;
begin
  insert into public.kbo_baseball_wallets (user_id)
  values (target_user)
  on conflict (user_id) do nothing;

  if not exists (
    select 1
    from public.kbo_baseball_ledger
    where user_id = target_user
      and reference_key = 'TEST_GRANT_5000_V1'
  ) then
    update public.kbo_baseball_wallets
    set balance = balance + grant_amount,
        lifetime_earned = lifetime_earned + grant_amount,
        updated_at = now()
    where user_id = target_user
    returning balance into new_balance;

    insert into public.kbo_baseball_ledger (
      user_id,
      amount,
      balance_after,
      transaction_type,
      reference_key,
      description
    ) values (
      target_user,
      grant_amount,
      new_balance,
      'TEST_GRANT',
      'TEST_GRANT_5000_V1',
      '테스트 계정 최초 야구공 지급'
    );
  end if;
end $$;

-- 확인
select user_id, balance, lifetime_earned, lifetime_spent, updated_at
from public.kbo_baseball_wallets
where user_id = 'b07e1249-c197-4d0c-9e77-ba310c6147bc';

select amount, balance_after, transaction_type, reference_key, description, created_at
from public.kbo_baseball_ledger
where user_id = 'b07e1249-c197-4d0c-9e77-ba310c6147bc'
order by created_at desc;
