import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
export const dynamic="force-dynamic";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL||"",pub=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"",secret=process.env.SUPABASE_SECRET_KEY||"";
const pc=()=>createClient(url,pub,{auth:{persistSession:false,autoRefreshToken:false}}),ac=()=>createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});
async function userOf(r:NextRequest){const t=(r.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!t)return null;const {data}=await pc().auth.getUser(t);return data.user||null}
function nameOf(u:any){return String(u?.user_metadata?.nickname||u?.user_metadata?.name||u?.email?.split("@")[0]||"KBO 팬").trim().slice(0,30)}
async function recount(a:any,postId:string){const {count}=await a.from("kbo_community_comments").select("*",{count:"exact",head:true}).eq("post_id",postId).eq("is_deleted",false);await a.from("kbo_community_posts").update({comment_count:count||0}).eq("id",postId);return count||0}
export async function GET(r:NextRequest){try{const id=String(r.nextUrl.searchParams.get("postId")||"").trim();if(!id)return NextResponse.json({ok:false,error:"POST_ID_REQUIRED"},{status:400});const u=await userOf(r),a=ac(),{data,error}=await a.from("kbo_community_comments").select("*").eq("post_id",id).order("created_at",{ascending:true});if(error)throw error;const rows=data||[],ids=rows.map((x:any)=>x.id);let liked=new Set<string>();if(u&&ids.length){const {data:l}=await a.from("kbo_community_comment_likes").select("comment_id").eq("user_id",u.id).in("comment_id",ids);liked=new Set((l||[]).map((x:any)=>x.comment_id))}return NextResponse.json({ok:true,comments:rows.map((x:any)=>({...x,likedByMe:liked.has(x.id),mine:u?.id===x.user_id,content:x.is_deleted?"삭제된 댓글입니다.":x.content}))})}catch(e){console.error(e);return NextResponse.json({ok:false,error:"COMMENT_LOAD_FAILED"},{status:500})}}
export async function POST(r:NextRequest){try{const u=await userOf(r);if(!u)return NextResponse.json({ok:false,error:"LOGIN_REQUIRED"},{status:401});const b=await r.json(),postId=String(b.postId||"").trim(),content=String(b.content||"").trim(),requested=String(b.parentId||"").trim()||null;if(!postId||!content||content.length>1000)return NextResponse.json({ok:false,error:"INVALID_COMMENT"},{status:400});const a=ac();let parent_id=null,reply_to_user_id=null,reply_to_name=null;if(requested){const {data:t}=await a.from("kbo_community_comments").select("id,post_id,parent_id,user_id,author_name").eq("id",requested).maybeSingle();if(!t||t.post_id!==postId)return NextResponse.json({ok:false,error:"REPLY_TARGET_NOT_FOUND"},{status:404});parent_id=t.parent_id||t.id;reply_to_user_id=t.user_id;reply_to_name=t.author_name}const {data,error}=await a.from("kbo_community_comments").insert({post_id:postId,user_id:u.id,author_name:nameOf(u),content,parent_id,reply_to_user_id,reply_to_name}).select("*").single();if(error)throw error;const n=await recount(a,postId);return NextResponse.json({ok:true,comment:{...data,mine:true,likedByMe:false},commentCount:n})}catch(e){console.error(e);return NextResponse.json({ok:false,error:"COMMENT_CREATE_FAILED"},{status:500})}}
export async function PATCH(r:NextRequest){try{const u=await userOf(r);if(!u)return NextResponse.json({ok:false,error:"LOGIN_REQUIRED"},{status:401});const b=await r.json(),id=String(b.id||"").trim(),content=String(b.content||"").trim();if(!id||!content||content.length>1000)return NextResponse.json({ok:false,error:"INVALID_COMMENT"},{status:400});const a=ac(),{data:c}=await a.from("kbo_community_comments").select("user_id,is_deleted").eq("id",id).maybeSingle();if(!c)return NextResponse.json({ok:false,error:"COMMENT_NOT_FOUND"},{status:404});if(c.user_id!==u.id)return NextResponse.json({ok:false,error:"FORBIDDEN"},{status:403});if(c.is_deleted)return NextResponse.json({ok:false,error:"COMMENT_DELETED"},{status:400});const {data,error}=await a.from("kbo_community_comments").update({content,updated_at:new Date().toISOString()}).eq("id",id).select("*").single();if(error)throw error;return NextResponse.json({ok:true,comment:{...data,mine:true}})}catch(e){console.error(e);return NextResponse.json({ok:false,error:"COMMENT_UPDATE_FAILED"},{status:500})}}
export async function DELETE(r:NextRequest){try{const u=await userOf(r);if(!u)return NextResponse.json({ok:false,error:"LOGIN_REQUIRED"},{status:401});const id=String(r.nextUrl.searchParams.get("id")||"").trim(),a=ac(),{data:c}=await a.from("kbo_community_comments").select("id,post_id,user_id").eq("id",id).maybeSingle();if(!c)return NextResponse.json({ok:false,error:"COMMENT_NOT_FOUND"},{status:404});if(c.user_id!==u.id)return NextResponse.json({ok:false,error:"FORBIDDEN"},{status:403});const {count}=await a.from("kbo_community_comments").select("*",{count:"exact",head:true}).eq("parent_id",id);if((count||0)>0){const {error}=await a.from("kbo_community_comments").update({is_deleted:true,content:""}).eq("id",id);if(error)throw error}else{const {error}=await a.from("kbo_community_comments").delete().eq("id",id);if(error)throw error}const n=await recount(a,c.post_id);return NextResponse.json({ok:true,commentCount:n})}catch(e){console.error(e);return NextResponse.json({ok:false,error:"COMMENT_DELETE_FAILED"},{status:500})}}